import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./_components/navigation/Navbar";
import Footer from "./_components/footer/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${raleway.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neutral-100">
        {/* Navigation */}
        <Navbar />
        {/* Main content */}
        <main className="flex flex-col flex-1">
          <Providers>{children}</Providers>
        </main>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
